# Pull request CI pipeline for Osprey
# Triggers for each pull request into the master branch
# Starts with a quick Full PRESS job
# If the first stage is successful a Full MEGA job is triggered

trigger: [ master ]
pr: [ master ]

pool: 'Default'

stages:
- stage: FullPRESS
  jobs:
  - job: FullPRESS
    steps:
    - script: matlab -nodisplay -wait -nosplash -r "addpath(genpath('C:\CI-agent\_work\2\s')); FullPRESS; quit"
      displayName: 'Full PRESS with Segmentation & GUI'

- stage: FullMEGA
  jobs:
  - job: FullMEGA
    steps:
    - script: matlab -nodisplay -wait -nosplash -r "addpath(genpath('C:\CI-agent\_work\2\s')); FullMEGA; quit"
      displayName: 'Full MEGA add Segmentation & GUI'
